### ISSUE TITLE
希望作者开讨论模块，对于有些建议和交流提Issues 还是不太适合

### ISSUE THREAD

**Issue by Yunkou** [haixiangyan/jest-tutorial#12]
RT

**Comment by haixiangyan** [comment]
讨论模块是指？是希望在官网的 vuepress 里添加评论区么？

**Comment by aloha66** [comment]
> 讨论模块是指？是希望在官网的 vuepress 里添加评论区么？

他意思应该是github的discussions，我不清楚开这个需要什么条件。
![image](https://user-images.githubusercontent.com/20942781/171016995-32ffbd5d-dfcb-4cf6-aa54-0feed778e0c1.png)

**Comment by haixiangyan** [comment]
@aloha66 感谢~
@Yunkou 已添加 discussion 模块 https://github.com/haixiangyan/jest-tutorial/discussions
