### ISSUE TITLE
Three discussions

### ISSUE THREAD

**Issue by SedationH** [haixiangyan/jest-tutorial#16]
1. When  I read this [ React Hook 测试 chapter](http://github.yanhaixiang.com/jest-tutorial/basic/hook-test/#react-hook-%E6%B5%8B%E8%AF%95) and compared it to the official documentation. I found that @testing-library/react itself provides the [API](https://testing-library.com/docs/react-testing-library/api#renderhook) for hooks. This feature is introduced [here](https://github.com/testing-library/react-testing-library/compare/v13.0.1...v13.1.0). You can refer to my practice [here](https://github.com/SedationH/hooks/blob/84427f9187/tests/hooks/useCounter.test.tsx#L2) for details usage.

2. 
> 注意：由于 inc 里面的 setState 是一个异步逻辑，因此我们在 @testing-library/react 提供的 act 里调用它。

 I would like to add a [reference](https://reactjs.org/docs/testing-recipes.html#act) to act here, and emphasize on behavior that "[act()](https://reactjs.org/docs/test-utils.html#act) that makes sure all updates related to these “units” have been processed and applied to the DOM before you make any assertions"

3. why `result.current[1].dec(1);`, I think it should be `result.current.dec(1)`, like ref. Refer to [here](https://github.com/SedationH/hooks/blob/84427f9187/tests/hooks/useCounter.test.tsx#L33)

**Comment by haixiangyan** [comment]
1. Hook 的章节最后有说到这个方法，但这个方法不是万能的，最后用 `useQuery` 举了例子
2. 我加个引用
3. 因为我例子里的 `useCounter` 返回的是一个数组，所以需要 `[0]`，按照你的来就好~

**Comment by SedationH** [comment]
（果然还是中文香
1. 我这里想说的是在[这个版本](https://github.com/testing-library/react-testing-library/compare/v13.0.1...v13.1.0)后，不需要引入`npm i -D @testing-library/react-hooks@8.0.0`来进行 hooks支持了，因此我觉得这样一个入口也看着统一一些、并且和当前文档一致
2. 好的
3. 是的，我没看仔细

感谢，启发很多

**Comment by haixiangyan** [comment]
我试了一下新版本，它要和 react@18 的版本一起使用，这里不想用不太稳定的版本，所以还是用旧的为主。我会在文档里添加一个关于新版本的说明。
