### ISSUE TITLE
basic/navigation/README.md 有笔误

### ISSUE THREAD

**Issue by kiinlam** [haixiangyan/jest-tutorial#20]
https://github.com/haixiangyan/jest-tutorial/blob/e1b7104e8bb4a735b086509742b6dbe7a5dd346f/docs/basic/navigation/README.md?plain=1#L184

https://github.com/haixiangyan/jest-tutorial/blob/e1b7104e8bb4a735b086509742b6dbe7a5dd346f/docs/basic/navigation/README.md?plain=1#L272

这里的文件名 `src/utils/getSearchObj.ts` 应该笔误了吧，正确应该是 `src/tests/utils/getSearchObj.test.ts`

**Comment by haixiangyan** [comment]
感谢！已修正。
