### ISSUE TITLE
三种-mock-思路 中 tests/mockServer/handlers.ts 代码错误，需要加 return

### ISSUE THREAD

**Issue by s5s5** [haixiangyan/jest-tutorial#22]
感谢海怪写这本书，非常好，非常有用，努力学习中。

今天在 [三种-mock-思路](https://github.yanhaixiang.com/jest-tutorial/basic/component-test/#%E4%B8%89%E7%A7%8D-mock-%E6%80%9D%E8%B7%AF) 中看到有个小错误：

> 先在 tests/mockServer/handlers.ts 里添加 Http 请求的 Mock Handler：

在这段话下的代码是错误的，我试了会提示

> [MSW] Expected response resolver to return a mocked response Object, but got undefined. The original response is going to be used instead.

正确代码应该在 `res(` 前加 `return` ，async 也可以不用加：

```ts
import { rest } from "msw";

const handlers = [
  rest.get("https://mysite.com/api/role", (req, res, ctx) => {
    return res(
      ctx.status(200),
      ctx.json({
        userType: "user",
      })
    );
  }),
];

export default handlers;
```

示例项目 jest-tutorial-example 中的 tests/mockServer/handlers.ts 中也有同样错误。

**Comment by haixiangyan** [comment]
了解，感谢指正，已修复~
