### ISSUE TITLE
组件测试-更多 Matchers，types 添加 @testing-library/jest-dom 报错

### ISSUE THREAD

**Issue by zhengbangbo** [haixiangyan/jest-tutorial#26]
跟随教程练习，`tsconfig.json` 中 types 添加 @testing-library/jest-dom  报错：

```shell
Entry point of type library '@testing-library/jest-dom' specified in compilerOptions
```

查询后找到 https://github.com/testing-library/jest-dom/issues/123#issue-481317447 

> 1. Add @types/testing-library__jest-dom to @testing-library/jest-dom dependencies
> 2. Add testing-library__jest-dom to DefinitelyTyped

按照这两条指示，测试运行成功。

这是[我的 commit](https://github.com/zhengbangbo/jest-starter/commit/ce5de0d3692b7d157287ffaabeca69a5a3c321cb#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0)。

**Comment by haixiangyan** [comment]
我 checkout 到这个 commit，使用 npm 安装，去掉 `@testing-library_jest-dom` 的一些配置，发现没有这个报错诶。目前还没想明白是什么原因，我在文档里加个 Hint，导到这个 Issue 上吧。
