### ISSUE TITLE
【Question】How to fix error: "Cannot log after tests are done. Did you forget to wait for something async in your test?"

### ISSUE THREAD

**Issue by kerwin-ly** [haixiangyan/jest-tutorial#40]
Hi 海怪大佬

我目前正在阅读[《Jest 实践指南》组件测试](https://github.yanhaixiang.com/jest-tutorial/basic/component-test/)这一章节，并且按照文章指引完成了相关测试代码的编写。但当我执行`npm run test`时，会有以下错误。

```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "Warning: An update to AuthButton inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at AuthButton (/Users/kerwin/Desktop/git-project/jest-demo/src/components/AuthButton/index.tsx:59:13)".



      at AuthButton (src/components/AuthButton/index.tsx:59:13)".
      at src/components/AuthButton/index.tsx:63:9
      at fulfilled (src/components/AuthButton/index.tsx:28:58)
```

期间我google了相关问题，一直没有得到理想的答案。

我也尝试启动了你的[jest-tutorial-example](https://github.com/haixiangyan/jest-tutorial-example)，没这个问题。

但当我把对应代码copy到自己仓库执行时，仍会出现这个错误。

这是我的[demo仓库代码](https://github.com/kerwin-ly/jest-demo/tree/feature/component)。

如果方便，希望可以帮忙解惑，感谢～

**Comment by haixiangyan** [comment]
看了下，应该是我这里有点问题的，正确的测试代码是这样：

```js
describe("AuthButton", () => {
  it("可以正常展示", async () => {
    render(<AuthButton>登录</AuthButton>);

    expect(await screen.findByText('普通用户登录')).toBeInTheDocument();
  });
});
```
稍微解释一下：`<AuthButton>` 里默认会有一个“登录”的文本，所以我那样写测试直接就通过了，而此时这个组件里的 `useEffect` 还没生效，所以等 `useEffect` 里的内容生效后就更新组件，但此时测试已经结束就报错了。

正确的写法应该是要等到有返回结果的时候再做 assertion，也即对 “普通用户登录” 进行 assert，这里之后我改下。

**Comment by kerwin-ly** [comment]
> 看了下，应该是我这里有点问题的，正确的测试代码是这样：
> 
> ```js
> describe("AuthButton", () => {
>   it("可以正常展示", async () => {
>     render(<AuthButton>登录</AuthButton>);
> 
>     expect(await screen.findByText('普通用户登录')).toBeInTheDocument();
>   });
> });
> ```
> 
> 稍微解释一下：`<AuthButton>` 里默认会有一个“登录”的文本，所以我那样写测试直接就通过了，而此时这个组件里的 `useEffect` 还没生效，所以等 `useEffect` 里的内容生效后就更新组件，但此时测试已经结束就报错了。
> 
> 正确的写法应该是要等到有返回结果的时候再做 assertion，也即对 “普通用户登录” 进行 assert，这里之后我改下。

那如何去`Mock HTTP`请求呢？`mockHttp.test.tsx`这个文件

**Comment by haixiangyan** [comment]
@kerwin-ly 后面的章节有讲到哈~
